version: '2'
services:
  db:
    image: ultra-db:latest
    environment:
      - POSTGRES_DB=ultra
    container_name: ultra-db
  ultrasound:
    image: bazel/server:ultrasound_server
    command:
      - -db.host=db
      - -db.name=ultra
      - -grpc.port=50051
    ports:
      - '50051:50051'
      - '8080:8080'
